version: '2'

services:
  #
  # Consul Service Discovery, ~50mb
  # @see https://hub.docker.com/r/progrium/consul/
  # @see https://www.consul.io/docs/agent/options.html
  #
  consul:
    command: -server -bootstrap -ui-dir /ui
    image: progrium/consul:latest
    ports:
      - 8400:8400  # rpc/rest
      - 8500:8500  # ui
      - 8600:53/udp   # dns
      - 172.17.0.1:53:53/udp  # dns

  #
  # Registrator Service Registry Bridge
  # @see https://hub.docker.com/r/gliderlabs/registrator/
  # @see http://gliderlabs.com/registrator/latest/
  #
  registrator:
    command: -ip=172.17.0.1 -internal consul://consul:8500
    image: gliderlabs/registrator:latest
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock"
    links:
      - consul

#service:
#  build: service
#  dns:
#    - 172.17.0.1
#  dns_search: service.consul
#  environment:
#    SERVICE_NAME: service
